name: mars_demo_app
description: Mars Sofware Technical Assestment.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  #state management
  get: ^4.6.1




  #utils  
  sizer: ^2.0.15
  shared_preferences: ^2.0.13



  #networking
  vexana: ^2.6.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0


flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
